@startumlGPS_Challenge -> Jugador: moverHaciaDireccion(unaDireccion: Direccion)Jugador -> Vehiculo: moverHaciaDireccion(unaDireccion: Direccion)Vehiculo -> Vehiculo: avanzar()Vehiculo -> Escenario: buscarEventoEnCuadra(cuadraActual: Cuadra)Escenario -> Cuadra: conseguirEvento()Escenario <-- Cuadra: NullVehiculo <-- Escenario: NullJugador <-- Vehiculo: cant_movimientos = 1Jugador -> Movimientos: actualizarMovimientos(cant:int)@enduml